### ISSUE TITLE
怎么关闭memcache ？？？？

### ISSUE THREAD

**Issue by Yonfan** [tanxinzheng/cas-sso#11]
怎么关闭memcache ？？？？

**Comment by tanxinzheng** [comment]
请查看cas-sso/cas-server-demo中的readme文档中自定义memcache扩展说明，将对应的配置注释即可。

**Comment by Yonfan** [comment]
我现在有二套独立的系统，想把他们做成单点登陆，不知所措。

**Comment by tanxinzheng** [comment]
搭一套cas系统，这两个独立的系统的认证对接cas认证系统就可以了
