### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by maidi1994** [tanxinzheng/cas-sso#9]
输入用户名和密码，显示登录不上，memcached连接不上

**Comment by tanxinzheng** [comment]
memcached的地址需要修改为你自己的memcached地址，配置文件如下（第111行）：
[https://github.com/tanxinzheng/cas-sso/blob/master/cas-server-demo/src/main/webapp/WEB-INF/cas.properties](https://github.com/tanxinzheng/cas-sso/blob/master/cas-server-demo/src/main/webapp/WEB-INF/cas.properties)
